### ISSUE TITLE
App Nap cannot be disabled for Anki 2.1.6

### ISSUE THREAD

**Issue by CarlosEvo** [FooSoft/anki-connect#102]
I tried to disable Anki's App Nap on macOS with no success. Anki's version is `2.1.6`.

I tired
```
defaults write net.ichi2.anki NSAppSleepDisabled -bool true
defaults write org.qt-project.Qt.QtWebEngineCore NSAppSleepDisabled -bool true
```
as instructed with no success.

I also tried:
```
defaults write org.qt-project.Qt.QtWebEngineProcess NSAppSleepDisabled -bool true
defaults write QtWebEngineProcess NSAppSleepDisabled -bool true
```

But App Nap still kicks in.

**Comment by majie1993** [comment]
Try 
```
defaults write net.ankiweb.dtop NSAppSleepDisabled -bool YES
```
The app's `CFBundleIdentifier` changed.

**Comment by FooSoft** [comment]
Thanks for the solution, @majie1993 I don't currently have access to MacOS so I wasn't able to troubleshoot this. I'll update the docs.
