### ISSUE TITLE
'ascii' codec can't encode character [...] in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by OoDeLally** [FooSoft/anki-connect#104]
Hello,
Thanks for this awesome API, it will really boost my language learning productivity.
I am learning Czech, and my deck is called `čeština` (meaning `Czech` in Czech).
When executing a `addNote` request:
IF
The deck name contains non-ascii characters (e.g. `č`)
AND
The requested deck doesn't exist
THEN
I get the following error `'ascii' codec can't encode character u'\\u010d' in position 0: ordinal not in range(128)`

How to reproduce:
```
curl localhost:8765 -X POST -d '{"action":"addNote","version":6,"params":{"note":{"deckName":"whateverDeckThatDoesntExistWithSpecialCharsLikeČ","modelName":"Basic (z)","fields":{"Front":"","Back":""},"tags":[]}}}' 
```

It works fine on every other cases:
- If deck doesnt exist but only contains ascii characters.
- If deck contains non-ascii characters but exists.

Thanks for any help :-)

**Comment by FooSoft** [comment]
Which version of Anki are you using? I'm on Version 2.0.52, and I cannot reproduce this issue.

**Comment by OoDeLally** [comment]
I was using 2.0.32 from the Linux Mint Software Manager.
Now I installed 2.1.8 from anki website, and it work flawlessly.
Cheers.
