### ISSUE TITLE
Documentation Request for Query parameters

### ISSUE THREAD

**Issue by KellyJohnBraun** [FooSoft/anki-connect#120]
I can't seem to find any documentation of useable query parameters besides `deck`.
Is it possible to query note field?
```
{
    "action": "findCards",
    "version": 6,
    "params": {
        "query": "deck:current"
    }
}
```

**Comment by FooSoft** [comment]
This is just any query string that you can enter into the deck browser; it's not specific to AnkiConnect. I don't know if Anki provides documentation of query strings, but that would probably be a good place to look :+1:

**Comment by KellyJohnBraun** [comment]
Thanks you for the quick response, I've found what I'm looking for. Keep up the good work!
