### ISSUE TITLE
Security: restrict CORS to localhost

### ISSUE THREAD

**Issue by andersonDadario** [FooSoft/anki-connect#130]
Hi all,

Currently CORS allow all origins.
By default it would be better to either disable or restrict to localhost.

Ideally it should be configurable, otherwise any malicious website can mess up with your Anki and also your computer.

Any questions, please let me know.
Anderson

**Comment by andreaskienle** [comment]
Can we make this configurable? I'm working on a web site which lets you add cards to Anki from different sources. Now this doesn't work anymore without disabling CORS in the browser altogether.

**Comment by FooSoft** [comment]
It is actually already configurable as is via the `ANKICONNECT_CORS_ORIGIN` environment variable. That being said, it might be a less than user-friendly way of doing so. For obvious reasons, we cannot make this configurable through the API itself; what did you have in mind?

We might have come to a point where we must have some sort of configuration UI in the plugin.

**Comment by andreaskienle** [comment]
There is already kind of a UI for plugin settings: In the Add-ons dialog there's a "Config" button where you can provide a text in JSON format. It is used by some plug-ins e.g. [Advanced Browser](https://ankiweb.net/shared/info/874215009) or [Add note ID](https://ankiweb.net/shared/info/1672832404). Could we use this for the CORS settings?

**Comment by andersonDadario** [comment]
The main goal of this PR was to add some security against malicious
websites that could abuse Anki connect api.

If you are going to use CORS with *, it would be great to at least add some
basic authentication to consume Anki connect api.

It’s easier to add this small control now rather than later :)

Andreas Kienle <notifications@github.com> schrieb am So. 5. Jan. 2020 um
18:25:

**Comment by FooSoft** [comment]
@andreaskienle I did not know about that -- this must be something relatively new. Back in the dark days when I wrote this extension there was nothing like this. I will investigate this possibility. Basic authentication can probably be something as simple as sending a password field for every single request (along with action).

**Comment by FooSoft** [comment]
@andersonDadario @andreaskienle I've updated AnkiConnect to have settings and a basic authentication mechanism. Let me know if it is sufficient for your guys' goals.

**Comment by andreaskienle** [comment]
@FooSoft Yes, this works! Thank you!
I think an even better solution would be to allow a set of origins in the plugin config, so the user doesn't have to switch around the config settings for different domains. [Here](https://stackoverflow.com/a/1850482/139355)'s described how to do this in principle.

**Comment by andersonDadario** [comment]
Only logged in GitHub today, sorry. Looks good. I took some time to find it hehe.

https://github.com/FooSoft/anki-connect/blob/dc8494f0fe01cc8d08a083f8677af5d0064af818/plugin/__init__.py#L86
