### ISSUE TITLE
Support apkg export

### ISSUE THREAD

**Issue by markusreil** [FooSoft/anki-connect#139]
Would be nice to be able to export collections that were created through the API.

I'll try to set up the dev environment and give it a go myself.

**Comment by FooSoft** [comment]
Yup, go for it :+1: 
Let me know if you have any questions, but in general, the hardest part is just finding the correct code to do what you want in Anki itself.

**Comment by markusreil** [comment]
Hi, I forked and created a PR.
Let me know what you think and if there's anything you want me to change.

Thanks,
Markus
