### ISSUE TITLE
RuntimeError when importing both PyQt4 and 5 inside anki 2.1

### ISSUE THREAD

**Issue by dequis** [FooSoft/anki-connect#14]
I have both pyqt4 and pyqt5 installed, so the ImportError check won't help here.

```
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 47, in loadAddons
    __import__(file.replace(".py", ""))
  File "/home/dx/.local/share/Anki2/addons21/AnkiConnect.py", line 53, in <module>
    from PyQt4.QtCore import QTimer
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class
```

This works for me:

```python
try:
    QTimer = aqt.QTimer
    QMessageBox = aqt.QMessageBox
except AttributeError:
    try:
        from PyQt4.QtCore import QTimer
        from PyQt4.QtGui import QMessageBox
    except ImportError:
        from PyQt5.QtCore import QTimer
        from PyQt5.QtWidgets import QMessageBox
```

(Also, thanks for writing this plugin and yomichan! I was looking for a webextensions replacement to rikaichan, didn't actually expect this upgrade in functionality!)

**Comment by FooSoft** [comment]
Yeah, using `import` to determine if we are on the alpha release was probably not the best idea. I've made a [simple change](https://github.com/FooSoft/anki-connect/commit/55174730727506a0c6fbe9c5ffe3d67583f29ef5) that checks for Python 3 and uses that as the basis of determining which version of Anki we are on (stable is Python 2, alpha is Python 3). If you can give it a whirl and make sure it works for you, I would appreciate it.

Yeah, I'm hoping that more folks discover this extension as they migrate off of the old, now depreciated API. It was a ton of work getting webextensions to do what is needed, but I think Yomichan is coming along nicely :smile:

**Comment by dequis** [comment]
Yup, that works. Thanks!
