### ISSUE TITLE
Missing webCorsOriginList field in configuration when downloading via ankiweb breaks anki-connect

### ISSUE THREAD

**Issue by mauamy** [FooSoft/anki-connect#140]
When you download the anki-connect addon via AnkiWeb (over the ID 2055492159) the configuration field 'webCorsOriginList' is missing. This breaks anki-connect, because it is not possible anymore to connect to anki-connect without this field since my MR #136. I included this field in *util.py* and *config.json* so I do not see why it is not existent when downloading it from AnkiWeb.

**Comment by FooSoft** [comment]
This is because getting the PR approved does not mean that a new version of AnkiConnect is automatically uploaded to AnkiWeb. I've just uploaded it now though, so things should work fine.
