### ISSUE TITLE
"storeMediaFile" returning error for syncDelete

### ISSUE THREAD

**Issue by pnewell** [FooSoft/anki-connect#146]
When I try to use storeMediaFile I am consistently getting the following error as of recent:

`Error: 'MediaManager' object has no attribute 'syncDelete'`

Looking at Anki's code, it does not look like media.py has syncDelete as of recent versions:
https://github.com/ankitects/anki/blob/cc44523449cda621c20f80e6583040deb57debb1/pylib/anki/media.py

**Comment by c-okelly** [comment]
The update function is here:

https://github.com/ankitects/anki/blob/master/pylib/anki/media.py#L117

**Comment by c-okelly** [comment]
Following code does seem to work:

```python
    def some_function(filename):
         try:
            self.media().syncDelete(filename)
        except AttributeError:
            self.media().trash_files([filename])
```

**Comment by c-okelly** [comment]
This is the new docs do anki addons on which hooks we should be using I think. Pretty sparse for a lot of the functionality really

https://github.com/ankitects/addon-docs/blob/master/hooks-and-filters.md

**Comment by FooSoft** [comment]
> 
> 
> Following code does seem to work. I'm still testing backward compatibility though
> 
> ```python
>     def some_function(filename):
>         try:
>             self.media().syncDelete(filename)
>         except AttributeError:
>             self.media().trash_files([filename])
> ```

@c-okelly that looks like it should work -- if you could open a PR with that change after verification, I would appreciate it :)

**Comment by toasted-nutbread** [comment]
Ran into this error with Yomichan's screenshot feature also. Confirming that @c-okelly's solution seemed to work.

https://github.com/FooSoft/yomichan/blob/f177e3699ae85bafa3a648f5c03fbb8e303a6be3/ext/bg/js/anki-note-builder.js#L112-L116

**Comment by c-okelly** [comment]
Just opened there. Only issue I really see is that the files are trashed rather then deleted.

It seems some parts of this project might have migrated to Rust

**Comment by FooSoft** [comment]
AnkiConnect with this change has now been pushed to AnkiWeb, thanks all :+1:
