### ISSUE TITLE
Feature Request: answerCard action

### ISSUE THREAD

**Issue by jaworekmichal** [FooSoft/anki-connect#148]
Currently API exposes operation `guiAnswerCard`. This operation depends on current GUI state.

In my opinion similar operation, but independent to GUI state, is missing.

Example request:

```
{
    "action": "answerCard",
    "version": 6,
    "params": {
        "ease": 1,
        "cardId": 1498938915662
    }
}
```

**Comment by Kubo2** [comment]
I have to back @jaworekmichal on this one. I have set to build a simple integrated learning app on top of Anki and being able to answer cards based on user's input is an essential AnkiConnect feature to accomplish this.

**Comment by dreambit** [comment]
+1 for this future.

**Comment by dit7ya** [comment]
Does anybody know how to answer a specific card given its ID, GUI or otherwise?
