### ISSUE TITLE
Please consider reverting changes introduced in commit 7ccfa79

### ISSUE THREAD

**Issue by zdzislaw-s** [FooSoft/anki-connect#156]
The change allows for creating duplicate notes in the collection. The change **does** stop creating duplicate notes if at least one of the note's card is in the target deck.

I would think that a better solution for the desired behaviour, i.e. allowing duplicate notes, would be to use the code for verifying that duplicate and empty cards are allowed (for example see documentation on the request `addNote`, `params.note.options.allow.allowDuplicate`). So rather than introducing changes as per 7ccfa79, you could modify Yomichan, namely `AnkiNoteBuilder.createNote()`, to include `options` in the note specification.

**Comment by FooSoft** [comment]
Adding @toasted-nutbread since this was his change

**Comment by toasted-nutbread** [comment]
Using `allowDuplicate = true` in Yomichan and reverting 7ccfa7938e68b85fcb7c4b2d370db003aa829e0f would cause Yomichan to not be able to know when a note has already been added to a deck. I.e. the "Add note" button would never appear disabled.

> The change allows for creating duplicate notes in the collection. The change **does** stop creating duplicate notes if at least one of the note's card is in the target deck.

The intention was to allow "duplicate" notes to be added to different decks. Is there some negative side effect that you are experiencing?

The subtle change to the default behaviour of the API may have been something that should have been put behind a new option. Making that change would work for Yomichan's use case. I can do that if nobody sees any issue with that.

**Comment by zdzislaw-s** [comment]
Anki by default flags duplicates as an anomaly and by design refrains from creating duplicate notes. This can be seen in many places, for example:
  1) when you add a new note (you get immediate highlight on the field that is not supposed to have duplicates), 
  2) in the **Browser** (again, Anki highlights the field where the duplication happens and displays a link to show you the duplicated notes), 
  3) when the **Browser** window is open you have a menu option "**Notes > Find Duplicates...**".

Also, Anki has a clear distinction on the purpose of the _Collection_ and the _Deck_. The _Collection_ is where the _Notes_ are stored, which also could be looked on as a database of your "knowledge", whereas the _Deck_ is a set of _Cards_ that are created based on the _Notes_ from the _Collection_. In a way _Deck_ is not really concerned about _Notes_ - it's function is to group _Cards_ and to provide parameters for reviewing these _Cards_. In that sense having a feature that implicitly allows for duplicating _Notes_ if one of the note's cards is in the target deck looks artificial to me. It also seems to go against intended purposes of the _Collection_ and the _Deck_.

In my specific case I work on two decks - one is where I keep cards that are already learned and are in the reviewing cycle, and the other is where I keep adding new cards (of course, these new cards are created implicitly/automatically when a new note is created and added). Again, please note that you are not adding a note to the deck - the note is added to the collection - what is added to the deck is card(s) that is/are created from the pair (_Note_, _Card Type(s)_) for a given _Note Type_. Now you can imagine that it is a problem for me when I work with Yomichan (kudos to you guys for the great soft, BTW :+1: :+1: :+1:) and Yomichan displays to me that the word that I'm looking at is not in my collection yet. Well, it may be there (in the non-target deck that is) and it may happen to be a duplicate that I'd prefer to avoid.

What I'm suggesting is to modify Yomichan to have an option available to the user where they explicitly indicate their desire for having duplicate notes (in their collection). This would achieve your intention of allowing '"duplicate" notes to be added to different decks' - you would only need to tick a check box for this happen. And as I understand, the code in AnkiConnect, even without the commit in question, would handle things as intended.

Hopefully the above makes sense and sorry for maybe being to verbose :wink:

**Comment by zdzislaw-s** [comment]
Ah, and this is what I do now to workaround _my_ problems:
```py
class AnkiConnect:
    .
    .
    .
    def isNoteDuplicateOrEmpty(self, note):
        result = note.dupeOrEmpty()
        return (result == 2 or result == 1)
    
    def createNote(self, note):
        .
        .
        .
        # zdz@22/4/20: duplicateOrEmpty = self.isNoteDuplicateOrEmptyInDeck(ankiNote, deck)
        duplicateOrEmpty = self.isNoteDuplicateOrEmpty(ankiNote)
```

**Comment by toasted-nutbread** [comment]
The problem I encountered is that duplicates are checked for using only the first field. This means that the key could be the same, but the actual card contents could be different. So while the cards could be identical, this is not necessarily the case.

![dupe](https://user-images.githubusercontent.com/11037431/80165185-eae38280-85a8-11ea-93ab-516db7c5a119.gif)

**Comment by zdzislaw-s** [comment]
That looks like a limitation of `Note.dupeOrEmpty()`.

Would it be possible to extend Yomichan/AnkiConnect to have specification of fields are meant to be unique? For example `("Expression", "Reading")` (or in your case `("Front", "Back")`) would specify that `"Expression"` and `"Reading"` (or `"Front"`, `"Back"`) have to be unique. This would require extra logic in both Yomichan and AnkiConnect (and possibly stopping on relying on `Note.dupeOrEmpty()`) and be a rather major undertaking. Anyway, my modest two cents :wink:

**Comment by toasted-nutbread** [comment]
> Well, it may be there (in the non-target deck that is) and it may happen to be a duplicate that I'd prefer to avoid.

Forgot to reply to this, but this sounds like something that I should add an option in Yomichan for if the AnkiConnect API is updated.

> That looks like a limitation of `Note.dupeOrEmpty()`.

It is. The implementation of `isNoteDuplicateOrEmptyInDeck` was largely copied from [`dupeOrEmpty`](https://github.com/ankitects/anki/blob/ab1f2429a77d1c366f4f4b44b0cb67ec95025f54/pylib/anki/notes.py#L184-L199).

> Would it be possible to extend Yomichan/AnkiConnect to have specification of fields are meant to be unique?

It's possible, but as you mention, additional effort for both Yomichan and AnkiConnect. I would be satisfied by reverting default behaviour and adding an option to control deck-vs-collection uniqueness, which would seem to address both your use case and mine.

Total card uniqueness could be addressed later if/when there is an explicit need for it.

**Comment by zdzislaw-s** [comment]
Would be happy with such an interim solution too.
