### ISSUE TITLE
Tags are formatted oddly

### ISSUE THREAD

**Issue by matthewwoo** [FooSoft/anki-connect#165]
Another issue I found is when I try to add tags to each of the cards via a list they don't render correctly in the anki app see here. 
![image](https://user-images.githubusercontent.com/63312834/80920072-4c7ebc00-8d22-11ea-94fd-e5795356d70b.png)

Here is an example of a list I'm passing through the tags params -> https://github.com/matthewwoo/kindle_anki/blob/master/test.py

**Comment by snoyes** [comment]
To demonstrate that this is a bug with AnkiConnect, please share a screenshot showing how those same tags render correctly when you add them directly within Anki.

**Comment by matthewwoo** [comment]
Here is an example tags rendering correctly -> 
![image](https://user-images.githubusercontent.com/63312834/81397319-ec9a6380-90db-11ea-9d41-0f5e5f5eedb5.png)

**Comment by snoyes** [comment]
AFAIK, Anki does not permit tags which contains spaces. For this particular example, the words just happen to be in alphabetical order. You actually have four tags on this note:
"Design," (note the comma)
"Mental"
"Models," (note the comma)
"Product"

Try editing the tags on that note to, "Design, Mental Experiment, Product" and see if Anki does not change that to "Design, Experiment, Mental Product"

This isn't an AnkiConnect bug; it's Anki's design.

**Comment by matthewwoo** [comment]
Cool thanks, appreciate it.
