### ISSUE TITLE
[feature request] multi-thread support

### ISSUE THREAD

**Issue by ninja33** [FooSoft/anki-connect#2]
Just wondering if anki-connect can support multi-thread to improve performance. 

Understood it was originally designed  to support yomichan extension which performs "one click, one card" function. Actually, It can be extended as a standard interface to support other app's batch cards importing interface. I tried to export Excel sheet by using VBA XMLHttpRequest lib, but the embedded socket server performance is very poor. After 20 cards, It definitely would be blocked.

I found a simple, but not completed project here. https://github.com/pbkhrv/anki-http-server
don't know it will help or not.

**Comment by FooSoft** [comment]
There are two main reasons for why I made the decision to make anki-connect single threaded:

* Anki is not thread safe (and I don't think the underlying sqlite database is either). Making it work in a threaded context would mean adding many synchronization primitives all throughout Anki code.
* Python's threading model is broken thanks to the Global Interpreter Lock (can only execute one Python instruction at a time); it's only useful if you are IO bound (which on a loopback connection is never going to be an issue).

This plugin doesn't actually have to do very much work on itself, and the issue you are experiencing is probably related to the throttling mechanism:

```
    def __init__(self, interval=25):
        self.anki = AnkiBridge()
        self.server = AjaxServer(self.handler)
        self.server.listen()

        self.timer = PyQt4.QtCore.QTimer()
        self.timer.timeout.connect(self.advance)
        self.timer.start(interval)
```

We only advance the state of the plugin once every 25ms at this point. Ideally that would not be a constant, but we would throttle the plugin dynamically based on request throughput. You could set the timer to 1ms and see if it helps your problem. Setting the timer to a low value has a negative side-effect of causing high CPU usage, which will suck for people using the extension on a laptop battery.

By the way, by being blocked, do you mean that anki-connect stopped processing commands entirely, or it was going at a slow rate? If it was completely stopped, then there is probably just a bug somewhere that we need to take care of.

The project you linked looks interesting, but based on the amount of code, it seems a little bit over-engineered for our purposes. We don't need to host the New York Times from within Anki, just respond to some simple requests ; )

**Comment by ninja33** [comment]
blocked, I mean it was totally stopped.

For that linked project, I think it only contains actually fewer than 20 lines code(_init_.py #164-184). as for other files, like cookie and itty.py, it just copied framework in project for less external dependency.

Anyway, thanks your feedback. I still have one more question. Would you still support anki-connect after dae upgrade Anki desktop to version 2.1. Seems Anki 2.1 would be built on Python 3.5/Qt5, just don't know if it will break current anki-connect function or not.

**Comment by FooSoft** [comment]
Sounds like a bug -- if you can provide a repro for me, I'll fix it up (probably something really simple).

Regarding Anki 2.1, I have to admit that I've been a little bit out of the loop (mostly working on Yomichan Chrome these days), so I didn't know that it's was going to be significant update -- thanks for putting it on my radar. I think the code will work fine as is with Python 3.5, but I do have some concerns that some of the Anki internals that I'm messing around with have been refactored, renamed, etc. Regardless, I will definitely support anki-connect, since due to the limitations of AnkiWeb, I think it's still the best way to automate flashcard creation. 

I'll play around with the beta client this weekend and see how broken things are.

**Comment by ninja33** [comment]
That's Excel VBA code which I used to commit over 100 concurrent connections to Anki-connect. Let's just forget it. 

Well, considering the performance and thread safety issue you mentioned, Instead of calling `addNote` function repeatedly, I am asking someone help add `addNotes` interface by leveraging Anki `importNotes` function. That will be more efficient.

Ankiweb interface was changed again last night to enable csrf token.  I had to apply another quick patch to fix this issue. To be honest, the Ankiweb interface implemented in our extension already violated ToS. So, It's not going to be a long term solution unless dae publishes an official  API. That's why anki-connect is such important for overall working flow. 

Thank you for your consideration of continue supporting anki-connect.

**Comment by FooSoft** [comment]
Thanks again for letting me know about the AnkiWeb breakage, I really appreciate it. You are right in that this interface may be on borrowed time. If the login page gets a CAPTCHA it will basically be game over as far as we are concerned. For the time being, I guess it's just a game of AnkiWeb being changed and us playing catch-up. Maybe I need to add some sort of automated test to find breakage... I honestly don't know why dae has a problem with this kind of usage, we don't make any more requests than the normal user would. By the way, you may want to check out my version of `ankiweb.js`. I made it be very robust (handles the user getting logged out at any point in the process), and it uses promises to make it easy to chain with other code. I also got custom dictionary importing, which is pretty neat too :smile: 

I'll definitely add an `addNotes` method, should be really simple. If you have any other suggestions about what would be helpful for you, let me know (I can probably do a couple of other things while I'm poking around in the code). If we lose access to AnkiWeb, having a good API for anki-connect will be ever-more important.

**Comment by ninja33** [comment]
Thanks your suggestion. Since your effort to use IndexDB and "promises", I have lost tracking of your major code already. 

I only had some knowledge of programming language C around 10 years ago. Actually, I just started studying JavaScript while trying to customize Yomichan  on June 2016. Fortunately, I knew how to find what I want on Google.  

Definitely, I will try to clean up my code if I build up much knowledge and understanding of OO and async programming. You know what? in my code, I just followed your workflow to switch anki-connect and ankiweb by using old C style `if-then-else`. polymorphism, class member function override, chain async function return. Well, all these things make me headache. So far, I barely can make it work. :cry: 

oh, forgot to mention that my extension firefox branch passed review (average 2 weeks in review waiting list, If failed, then another 2 weeks) and listed on [AMO](https://addons.mozilla.org/en-US/firefox/addon/anki-%E5%88%92%E8%AF%8D%E5%88%B6%E5%8D%A1%E5%8A%A9%E6%89%8B/?src=ss) already. If you want to pass AMO review quickly, I can share you some experiences blow:
1. Except license, you need another document called "Privacy Policy"
2. You need upload all your source, but the JSON file size must be less than 4M each(noticed you already split edict.json)
3. You need upload your handlebars pre-compiled source(html) as additional files, not just template.js. because that's not human readable (or understandable?) format.
4. You can not use {{{.}}} in your handlebar source, because they requestd that everything must be escaped for security purpose. As an alternative solution, you can make your owner version register helper and escape first then return safe string from that helper. you can find my [term.html](https://github.com/ninja33/anki-dict-helper/blob/dev/tmpl/term.html) line#36 and [yomichan.js](https://github.com/ninja33/anki-dict-helper/blob/dev/ext/bg/js/yomichan.js) line#36-42

Hope this may help you.

**Comment by FooSoft** [comment]
In Yomichan, I just have three classes with the exact same signature; one for AnkiWeb, one for anki-connect and a "null" one that doesn't do anything. I then just have a single reference that points to the Anki interface the user wants to use, no switching required :smile: If I later want to add support for exporting to Google Docs or something, it will just be a matter of writing another class that supports export to that backend.

Thank you for your insight about the Firefox approval process -- I didn't even realize that there was one... After I get through a couple of remaining issues left on this version, I'll probably start porting it to that browser, it's something that I'm asked about quite a lot.

**Comment by FooSoft** [comment]
Back to the topic at hand -- that was fast:

![])(http://imgur.com/0ErhRPkl.png)

**Comment by ninja33** [comment]
Yes, mine is also suspended.  :disappointed: 
I don't want to play this game any more. Just let it be till dae publish his standard API.

**Comment by FooSoft** [comment]
Yeah. Removing this feature from the extension now, would not be good if other people got suspended because of this.
