### ISSUE TITLE
Noob question: how to allow CORS without browser extension?

### ISSUE THREAD

**Issue by ddfonseca** [FooSoft/anki-connect#201]
Hi, I'm not a developer but I can make some code. I tried everything I read on this github issues and on Internet and didn't found HOW to allow CORS without browser extension. I only can make my AnkiConnect work with a browser extension that allow eveything.

I'm using JavaScript, so I'd like a code to run on browser.

Thanks

**Comment by ChickieDrake** [comment]
If you want to code JS use Node. Unless you have a specific reason to embed the function in a web page, that is not the best way to run JS.
If you REALLY want a web page, you'll likely need to create your own API for it (which you will probably want to do with Node anyway).

**Comment by ddfonseca** [comment]
Even if I just run on localhost? I think it could be a simple answer, but ok, If this is the way, I'll read more about it.

Thanks

**Comment by dit7ya** [comment]
If you are looking for using it in a Firefox extension, you can try adding 

`"permissions": ["http://127.0.0.1/*"],` to your `manifest.json`.
