### ISSUE TITLE
'DeckManager' object has no attribute 'dconf'

### ISSUE THREAD

**Issue by TineyseHefuronActeliaUrsaneItoluna** [FooSoft/anki-connect#202]
When sending this request, this is what I get at the end :

    POST http://localhost:8765/ HTTP/1.1
    User-Agent: vscode-restclient
    Content-Type: application/json
    accept-encoding: gzip, deflate
    content-length: 914
    
    {
      "version": 6,
      "action": "saveDeckConfig",
      "params": {
         "config": {
          "id": 1,
          "mod": 1595452524,
          "name": "Default",
          "usn": 0,
          "maxTaken": 60,
          "autoplay": true,
          "timer": 1,
          "replayq": true,
          "new": {
            "bury": false,
            "delays": [
              1,
              10
            ],
            "initialFactor": 2500,
            "ints": [
              1,
              4,
              0
            ],
            "order": 1,
            "perDay": 20,
            "separate": true
          },
          "rev": {
            "bury": false,
            "ease4": 1.3,
            "ivlFct": 1,
            "maxIvl": 36500,
            "perDay": 200,
            "hardFactor": 1.2,
            "minSpace": 1,
            "fuzz": 0.05
          },
          "lapse": {
             "delays": [
               10
            ],
            "leechAction": 0,
            "leechFails": 8,
            "minInt": 1,
            "mult": 0
          },
          "dyn": false
        }
      }
    }

response:

    HTTP/1.1 200 OK
    Content-Type: text/json
    Access-Control-Allow-Origin: http://localhost
    Content-Length: 74
    
    {
      "result": null,
      "error": "'DeckManager' object has no attribute 'dconf'"
    }

**Comment by snoyes** [comment]
https://github.com/FooSoft/anki-connect/blob/ab1f5184746b70e2b7186c332fa26b1e815073e9/plugin/__init__.py#L423-L427

Anki changed how the deck configurations are managed some time ago. dconf doesn't seem to exist anymore. I think the above should be something like:

```
        if not config['id'] in [str(d.id) for d in collection.decks.all_names_and_ids()]:
            return False

        collection.decks.save(config)
        collection.decks.updateConf(config)
```

References to dconf also appear in other methods.

**Comment by web1991t** [comment]
The issue still exists, is it possible to fix it?

**Comment by NSBum** [comment]
As others have noted, the issue is still open. Not knowing whether the maintainers are open to pull requests, I'll just put this out there as a temporizing solution. In `__init__.py` the code for `saveDeckConfig` should be:

```python
@util.api()
def saveDeckConfig(self, config):
    collection = self.collection()

    config['id'] = str(config['id'])
    config['mod'] = anki.utils.intTime()
    config['usn'] = collection.usn()
    if int(config['id']) not in [c['id'] for c in collection.decks.all_config()]:
        return False
    try:
        collection.decks.save(config)
        collection.decks.updateConf(config)
    except:
        return False
    return True
```
