### ISSUE TITLE
Info on findNotes's query parameter

### ISSUE THREAD

**Issue by eyeinsky** [FooSoft/anki-connect#211]
Is there a tutorial for what can be in the  `query` parameter for `findNotes` action?

Specifically, I'd like to find notes where the front field has a specific value. Searching this repo the only example is 'deck:some deck name'.

**Comment by snoyes** [comment]
https://docs.ankiweb.net/#/searching

**Comment by eyeinsky** [comment]
@snoyes Ah, right, thanks! It said that it has the same syntax as `guiBrowse`, but the [documentation for it](https://github.com/FooSoft/anki-connect/blob/master/actions/graphical.md) didn't say anything more.

**Comment by eyeinsky** [comment]
I created a pull request https://github.com/FooSoft/anki-connect/pull/224 here to make the docs clearer.

**Comment by eyeinsky** [comment]
The syntax of the query was cleared up in #224, closing.
