### ISSUE TITLE
Retrieve all card ids for given note ids

### ISSUE THREAD

**Issue by leoc** [FooSoft/anki-connect#222]
Hey there! Thanks for this beautiful package. It helps me a lot with my daily card generation :+1: 

I am using louietan/anki-editor which synchronizes org files to anki. This package references only the note id internally.

Now I would like to change the deck for a note. Unfortunately the `changeDeck` action only allows a `cards` parameter.

How do I find all card ids for a given note id to then update the specific cards?

![](https://media1.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif)

**Comment by leoc** [comment]
Oh my, six minutes and I find it in `notesInfo`.

Everything is awesome!


![](https://media0.giphy.com/media/xTiTnI07YKK6qjHgnm/giphy.gif)

**Comment by louwers** [comment]
It is not documented though.
