### ISSUE TITLE
No breakline when adding images to notes?

### ISSUE THREAD

**Issue by lthiet** [FooSoft/anki-connect#223]
Is there a way to disable the automatic break line in between images when one adds multiple images to a note?

**Comment by snoyes** [comment]
https://github.com/FooSoft/anki-connect/blob/c55281d67a2677fd1e37ccff6f235d396969072d/plugin/__init__.py#L562

**Comment by FooSoft** [comment]
Looks like it was added in this commit by @grepmew :
https://github.com/FooSoft/anki-connect/commit/06dff2110724787287e050299ebd5f82fd5f5a6d

I don't see any reason why we can't remove the markup.

**Comment by grepmew** [comment]
There's no particular reason this markup needs to be there. It can be removed.
