### ISSUE TITLE
Unable to mine cards using Nazeka 

### ISSUE THREAD

**Issue by MasonRepo** [FooSoft/anki-connect#245]
Hello,

I was curious if anyone else had a similar problem happen for them as well.   I'm currently using Nazeka's live mining feature with and whenever I try and mine a word an error pops up that says this: https://i.imgur.com/1hselnq.png 

It was working up until yesterday, I don't believe anything updated or anything like that so any help would be greatly appreciated!

**Comment by MasonRepo** [comment]
Nevermind it looks like it was an issue with Adblocker which is extremely odd as removing it fixed the issue.

**Comment by jacksonavery** [comment]
I can second this issue. Yomichan works, but takes much longer than usual.

**Comment by jacksonavery** [comment]
The issue seems to be with the JapanesePod101 audio source. Switching to "JapanesePod101 (alternate)" within Yomichan fixes the issue with slower load times. I'm unsure if something similar is possible within Nazeka, but in all fairness this is the ankiconnect repo, not the nazeka one.

**Comment by MasonRepo** [comment]
Oh yeah I was just wondering if this was an issue with a recent change to AnkiConnect or something within Nazeka that's causing them to not communicate with each other.

**Comment by MasonRepo** [comment]
JapanesePod101 is up which has fixed the mining issue.
