### ISSUE TITLE
Method updateNoteFields returns status 200 but data is not updated

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [FooSoft/anki-connect#251]
I am making this request:

`curl --location --request POST 'localhost:8765' \
--header 'Content-Type: text/plain' \
--data-raw '{
    "action": "updateNoteFields",
    "version": 6,
    "params": {
        "note": {
            "id": 1616590014938,
            "fields": {
                "Front": "new value",
                "Back": "new value"
            }
        }
    }
}' -v`

and receive response status code 200 and body null.

But the note is not updated.

**Comment by lazy-void** [comment]
@AnatoliiStepaniuk I checked and it works for me. What version of Anki and AnkiConnect do you use?

**Comment by AnatoliiStepaniuk** [comment]
Thanks, it turned out I was sending invalid body.

Would be helpful to receive a meaningful response from Anki Connect server in this case.

Closing this issue.
