### ISSUE TITLE
Is it possible to access the debugging console?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [FooSoft/anki-connect#258]
Hi,

I have a project in the summer that will involve function ankiconnect doesn't currently have.So I was looking at the code to see how to add them.

But I figured I might actually need access to the anki console as that might be easier than adding tons of new features.

In a dream world I would need at least : 
* burying notes
* adding flags to notes
* creating filtered decks
* emptying and rebuilding filtered decks

_**My question is the following, do you know if it's possible to add support for the ankiconsole from ankiconnect or is it forbidden somehow?**_

I think I would rather painstakingly add support to the console that having to code each new function. Especially because I don't know yet the full list of things I would need to add.

Thanks!

edit : to clarify. What I'm after is an action from ankiconnect that would receive python code and then execute it in anki's debugging console, then sometimes return values if I want to.

(if anyone doesn't know what this console is, there is a shortcut like "ctrl+:" on the main window of anki that makes it appear, the shortcut varies depending on your platform so you can check out the documentation to find yours)

**Comment by FooSoft** [comment]
So are you wanting to execute code sent to AnkiConnect? That sounds very very dangerous. Python code running inside of Anki is not sandboxed in anyway whatsoever, so bad applications could do anything as the current user on the system. That being said, what you are asking is definitely possible, it's just that arbitrary code execution is just not something I'd merge in. However, if what you are talking about is just a debugging tool, I think there would be no problems, and you can do absolutely anything you want inside of Anki when running as a plugin.

**Comment by thiswillbeyourgithub** [comment]
Thank you very much for your answer.

I understand this ability would seem dangerous but I don't see how that's more dangerous than any other anki addon. Your explanations would be very welcome.

Is there a compromise you might accept to merge in? I'm thinking the following mitigations :
* the code will not be run before a popup showing the commands is shown to the user
* enabling the console would be disabled by default in the config and would have to be enabled by the user.
* only accept some methods to be run, instead of allowing any code.

I don't understand why I seem to be the first one to want this feature. This seems like a time saver to be able to interact with anki console to speed up addon prototyping don't you think?

**Comment by FooSoft** [comment]
Sorry for the long reply -- I have no problems with this if the feature has to be explicitly enabled by the user, and there is sufficient messaging to explain that this is a developer feature and that they should try to not shoot themselves in the foot :)

**Comment by thiswillbeyourgithub** [comment]
Great to know! I will think about it more in the summer. Not sure that's the best way for my project but I'll keep it in mind.

It seems rather easy to add as it's actually just calling "exec", as you can see in line 1531 : https://github.com/ankitects/anki/blob/581480191acc512b64b7af67f4660e3a49355f9b/qt/aqt/main.py

Thanks a lot!
