### ISSUE TITLE
Not working after update

### ISSUE THREAD

**Issue by Geniusssmit** [FooSoft/anki-connect#268]
I've just updated AnkiConnect addon and I can't create anki cards anymore. This is what I have in yomichan settings. How to deal with it?
```
Enable Anki integration
Connection status: Anki error: 'AnkiConnect' object has no attribute 'decks'. Details…

{
    "action": "deckNames",
    "status": 200,
    "apiError": "'AnkiConnect' object has no attribute 'decks'"
}

Error: Anki error: 'AnkiConnect' object has no attribute 'decks'
    at AnkiConnect._invoke (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/js/comm/anki.js:207:31)
    at async AnkiConnect.getDeckNames (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/js/comm/anki.js:83:16)
    at async AnkiController._getDeckNames (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/js/pages/settings/anki-controller.js:272:28)
    ```

**Comment by Jesmaster** [comment]
I'm getting the same error. 

To reproduce:

`curl localhost:8765 -X POST -d "{\"action\": \"deckNames\", \"version\": 6}"`

results in 

`{"result": null, "error": "'AnkiConnect' object has no attribute 'decks'"}`

After the update. Going to http://127.0.0.1:8765/ in my browser I see `AnkiConnect v.6` so it's not a connection issue.

**Comment by FooSoft** [comment]
Gah, accidentally pushed a release that included some untested cleanup work. Should be fixed now, please reopen if you see any other issues.
