### ISSUE TITLE
Propose standard for handling releases / managing API version

### ISSUE THREAD

**Issue by CharlesHenry** [FooSoft/anki-connect#27]
With more and more changes going into this plugin, I think we need to devise a way to handle releases so that we can ensure that the functionality we require is in a certain version, without incrementing the API version every change.

The scenario here is that my app checks that API version 4 is running, but since changes are going in frequently there is a possibility that the user may or may not have the specific change I need in their version, even though they have version 4.

Once solution is to increment the API version on demand, when a dependant app is ready for a code release, so that we can be sure that the required functionality is present?

**Comment by techdavid** [comment]
I could implement an `areSupported` function to check if certain actions are present in the version running - would that work? e.g.

```
{
    "action": "areSupported",
    "params": {
        "actions": ["setLock", "removeLock", "imaginaryFutureAction"]
    }
}
```

would return:

```
[true, true, false]
```

(assuming Alex is happy with my latest PR)

**Comment by CharlesHenry** [comment]
@techdavid That sounds like an ingenious idea! What if there is a change to an existing function how could we handle that? I know it's an edge case but if we could think of a solution for such a scenario it would be good. Maybe falling back to changing the API version could suffice for such an edge case?

**Comment by techdavid** [comment]
As far as I'm aware changes like that don't happen often. Also, I only updated it to match the behaviour which was already documented ;)

However, one solution would be to have a version for each action, starting at 1, and increment it whenever an API-breaking change happens. So for example:

```
{
    "action": "supportedActions"
}
```
would return
```
{
    (all the other actions),
    "guiDeckOverview": 1,
    "guiDeckBrowser": 1,
    "guiDeckReview": 2
}
```

Only the actions which have changed since their inception would need to have a hard-coded version - for the others, we can just list all the attributes of the AnkiConnect class with the `@webApi` decorator and assume version 1.

**Comment by CharlesHenry** [comment]
I very much like the sound of this idea. As you have already kindly volunteered to pick this up, shall I leave this to you to implement?

**Comment by techdavid** [comment]
Sure, I will try to get this done later today!

**Comment by CharlesHenry** [comment]
Thanks a bunch! I really owe you one!

**Comment by FooSoft** [comment]
I've added a mechanism for version control in the latest release. Please see `README.md` for details.

**Comment by FooSoft** [comment]
I should add that the new approach allows for API deprecation, and API renaming all through the python decorator syntax. I should probably write some docs about that too... In any case, the easiest thing to do is just to watch the `error` field as that will report anything that goes wrong with your API invocation.

**Comment by CharlesHenry** [comment]
Hello @FooSoft, I'd like to add a field to guiCurrentCard and I'd like to do an API version check at start up rather than discovering that the new field is missing at a later time. Am I correct in thinking that we are only using the top level API_VERSION parameter for this at the moment?
