### ISSUE TITLE
guiBrowse returns error on Anki versions past 2.1.45

### ISSUE THREAD

**Issue by soameshi** [FooSoft/anki-connect#277]
I'm currently trying out the latest Anki (2.1.45+), and I noticed that the guiBrowse action in anki-connect returns an error now, regardless of what query I send it.

Example request
```
{
    "action": "guiBrowse",
    "version": 6,
    "params": {
        "query": "deck:current"
    }
}
```
Response
```
{
  "result": null,
  "error": "'MockModel' object has no attribute 'cards'"
}
```

Notably, the gui browser still changes to display "deck:current", but no card ids are returned, just the error. My guess is that this has to do with the browser changes in Anki 2.1.45, since "MockModel" was something introduced into Anki in that release. https://github.com/ankitects/anki/commit/e24f562f8c1f4235225f552cd8d531419303babd

Since my goal is to just change what the gui browser displays, I can probably get away with ignoring the error for now, but I thought I'd bring it up in case it's a problem for anyone else.

**Comment by Xinyu-Wu-0000** [comment]
```json
{
    "action": "findCards",
    "version": 6,
    "params": {
        "query": "deck:current"
    }
}
```
Card ids can be returned with find cards. But the `Front:good` can't be added to the `query`.
```python
Result: {'result': None, 'error': "findCards() got an unexpected keyword argument 'Front'"}
```

**Comment by Xinyu-Wu-0000** [comment]
I got the syntax wrong.
The `findCards` api is ok.
The correct syntax:
```json
{
    "action": "findCards",
    "version": 6,
    "params": {
        "query": "deck:English Word:lusty"
    }
}
```

not :
```json
{
    "action": "findCards",
    "version": 6,
    "params": {
        "query": "deck:English, Word:lusty"
    }
}
```

Don't put the comma between.
