### ISSUE TITLE
Latest Update Requires <= Anki 2.1.44

### ISSUE THREAD

**Issue by EnsignPayton** [FooSoft/anki-connect#321]
Updated addons and noticed AnkiConnect no longer loads. The meta.json now declares that it requires Anki <= 2.1.44, while I have 2.1.49 installed

**Comment by EnsignPayton** [comment]
Judging by https://github.com/FooSoft/anki-connect/issues/320 and comments over [here](https://ankiweb.net/shared/info/2055492159), looks like this issue may be exclusive to the AnkiWeb download

**Comment by EnsignPayton** [comment]
Resolved locally by setting `max_point_version` to 0 and `min_point_version` to -44.

If anyone happens upon this looking for a quick fix...

Navigate to addon install folder at `%appdata%\Anki2\addons21\2055492159`. Replace `meta.json` contents with the following:

```json
{"name": "AnkiConnect", "mod": 1651115158, "min_point_version": -44, "max_point_version": 0, "branch_index": 0, "disabled": false, "conflicts": [], "update_enabled": true}
```

Restart Anki

**Comment by FooSoft** [comment]
This should be fixed. AnkiWeb UI for releasing different code for different versions sucks.

**Comment by oakkitten** [comment]
I do wish they had api. I really like how I can publish an app to playstore just by pushing a tag.
