### ISSUE TITLE
AnkiConnect takes +-30 seconds to create a flashcard

### ISSUE THREAD

**Issue by boopnbop** [FooSoft/anki-connect#336]
I've been using AnkiConnect for a while now and this problem only came up today. It was never instant but it usually took around maybe 4 seconds for every card which never really bothered me. Today, though, It takes around 30-40 seconds to create a single card from Yomichan using AnkiConnect. I have deleted and reinstalled the plugin, turned Yomichan on and off, restarted and updated my computer, routed AnkiConnect to a new deck, and then to a brand new deck under a brand new user. None of this has worked though, I'm kind of all out of ideas at this point.

I use Windows. I have seen [this issue](https://github.com/FooSoft/anki-connect/issues/129), but they use a Mac and respond using a ton of code I don't understand. I'm not very tech savvy when it comes to this kind of stuff. Does anybody have any ideas?

**Comment by Ralino** [comment]
Hi, I had the same issue today, however, the reason (for me at least) seems to be fetching the audio, not the communication with Anki. That is, playing the audio in Yomichan also took that long. To fix this, select a different audio source in Yomichans settings, the default one (JapanesePod101) seems to be rather slow right now.
