### ISSUE TITLE
getDeckStats action not working

### ISSUE THREAD

**Issue by w1lford** [FooSoft/anki-connect#351]
I am using Anki 2.1.35 with AnkiConnect and the getDeckStats action isn't working. This is my POST request body:
```
{
    "action": "getDeckStats",
    "version": 6,
    "params": {
        "decks": ["A.I.C.O Incarnation"]
    }
}

```
I always get 'unsupported action' in the response. 

```
{
    "result": null,
    "error": "unsupported action"
}
```

**Comment by snoyes** [comment]
getDeckStats was added in May. Have you updated AnkiConnect since then?

**Comment by w1lford** [comment]
I installed AnkiConnect a week ago so I am certain I have the latest version.

**Comment by snoyes** [comment]
Looks like that endpoint isn't in the pre-2.1.45 version. Upgrade Anki to at least 2.1.45 (current latest is 2.1.54) and then use the latest AnkiConnect.

**Comment by w1lford** [comment]
I can confirm this endpoint works on Anki 2.1.45 with the latest AnkiConnect.
