### ISSUE TITLE
[feature request] add notes in batch with addNotes function

### ISSUE THREAD

**Issue by ninja33** [FooSoft/anki-connect#4]
discussed it before, just put a placeholder here.

while reading API, I noticed that `canAddNotes` function actually checked note status in batch already. So, as result, AnkiConnect definitely can have a function called `addNotes` which add notes in batch.

**Comment by FooSoft** [comment]
Just added `addNotes`, and updated the docs. I also made some updates to the documentation where the request params for `canAddNotes` and `addNote` were wrong.
