### ISSUE TITLE
Create guiExitAnki endpoint

### ISSUE THREAD

**Issue by tomasgodoi** [FooSoft/anki-connect#44]
It would be nice if we could exit anki through a rest api. When running inside Docker, I've managed to close it gracefully by sending the SIGINT signal, but I don't quite like that approach. If I could exit it through a REST API call it would be better (it would be more guaranteed it would close gracefully and the data saved successfully).

Do you guys think that makes sense? If so, I could develop a PR.

**Comment by FooSoft** [comment]
Seems like a good thing to add. Hopefully there is a way to implement it in a way that guarantees that the reply gets sent out before Anki terminates.
