### ISSUE TITLE
AnkiConnect is not listed as compatible with 2.1.x on AnkiWeb

### ISSUE THREAD

**Issue by tomasgodoi** [FooSoft/anki-connect#47]
It seems now you have to label it or something as compatible with Anki 2.1.x. I can't install it through the Anki 2.1.x UI.

**Comment by tomasgodoi** [comment]
It also seems that if you want to use Anki 2.1.x addons, you have to create a folder with a file named __init__.py. Of course you could do that transformation when uploading it to the AnkiWeb.

**Comment by FooSoft** [comment]
Fixed
