### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by Shadowlauch** [FooSoft/anki-connect#48]
Hey guys,

First of all thanks for the great plugin, saved me a lot of time!

One small thing I came across while trying to add nodes via the API. The documentation for adding notes has two errors:

1.  There is a comma after the the "Back" and "Tags" items `"Back": "back content",` & `"yomichan",` making the example malformed JSON
2. The audio section totally fails to mention the "fields" item which is necessary for the plugin to download the audio file

**Comment by FooSoft** [comment]
Fixed!
