### ISSUE TITLE
Get information of any card

### ISSUE THREAD

**Issue by kgoedert** [FooSoft/anki-connect#51]
Hi, 

It would be nice  to get information about any card (outside of review mode).

**Comment by tomasgodoi** [comment]
It's already supported:
https://github.com/FooSoft/anki-connect#finding-notes-and-cards

**Comment by tomasgodoi** [comment]
Maybe what you want is to retrieve the note fields? That would be useful to me too.

**Comment by kgoedert** [comment]
Yes. I need a specific field on a card

**Comment by tomasgodoi** [comment]
Well, maybe I can make a PR in the future if nobody does first.

**Comment by ReneBrals** [comment]
This is relatively easy to do: the `guiCurrentCard` endpoint already retrieves card data, so a new endpoint can just adapt that functionality to fetch specific card IDs instead of the currently reviewed card. Doing this for notes works in a similar way.

I have a Pull Request open for this.
