### ISSUE TITLE
post request with CURL windows

### ISSUE THREAD

**Issue by valuex** [FooSoft/anki-connect#54]
In the tutorial,  

`curl localhost:8765 -X POST -d '{"action": "deckNames", "version": 5}'  `

for CURL Windows, it should be given as:  

`curl localhost:8765 -X POST -d "{\"action\": \"deckNames\", \"version\": 5}"`

**Comment by FooSoft** [comment]
I updated the docs with your version since it should work fine on non-Windows systems as well.
