### ISSUE TITLE
adding images

### ISSUE THREAD

**Issue by kgoedert** [FooSoft/anki-connect#55]
Hi,

is there a way to add images to the cards, link the audio files?

Thanks

Kelly

**Comment by FooSoft** [comment]
Yeah, take a look at the [Media Storage API](https://foosoft.net/projects/anki-connect/#media-file-storage). Once your media is stored in Anki (be it image or audio data), you just reference it through the card using square brackets. To see what this looks like, try adding an image to a card manually and then seeing what markup is generated when you view the card in the deck browser. Feel free to reopen this if you have other concerns.

**Comment by bomcon123456** [comment]
Hello, Im currently trying to add an image from media with text, but I dont know the syntax, for eg, if I'm adding a sound, [sound:x.mp3] would do the trick.
When I tried to manually add the image (by dragging to the field), it shows only the image, not the text embedded. Can you show me the syntax? THANKS!
