### ISSUE TITLE
[feature request] a optional parameter for doe option.

### ISSUE THREAD

**Issue by ninja33** [FooSoft/anki-connect#6]
in line#371-372, there is a control to avoid duplication. 
```
        if not note.dupeOrEmpty():
            return note
```
But, sometimes, people need make duplicated cards while headword having multi-meaning. 
They want to make one card each time when they read it in different context.

![book](https://cloud.githubusercontent.com/assets/20181220/23839501/7b1bea96-07d9-11e7-999e-2705d573ed6b.png)

Currently, I hardcode it like below and distribute it in my learning English community to those who may want "duplicated card" feature.

```
        doe = note.dupeOrEmpty()
        if not doe or doe == 2:
            return note

```

Recently, I noticed you made some new code to detect version and upgrade itself.
So, I want to all my users can just keep same version( not customized)

**Comment by FooSoft** [comment]
Maybe things have changed, but it used to be that you could not even add notes that have a duplicate primary (first) field. How are you getting around this limitation? 

I think it would be cool if we could converge to using the same version of the AnkiConnect plugin. I think that we use it in almost the same way and we can just make some tweaks and use the same one.

**Comment by ninja33** [comment]
Well, if this is the case; the only workable way is to tweak head word, like book(1), book(2)

But, If people want to use Anki's {type:field name} function for spelling practice, that will be problem. 

Anyway, I also give users another choice in chrome extension option page. I added a {glossary-list} placeholder in field mapping section. Users can add all meaning of single word by using this placeholder.

**Comment by FooSoft** [comment]
Since several versions ago I group definitions. So even though the `expression` field is just `book`, you would have all of the definitions under it in the `glossary` section. 

If you don't want to go through that work you can just tell people to put `glossary` as the first field in their Anki model. Since the glossary will be unique people can add as many expressions as they want as long as they just have different glossaries.

**Comment by ninja33** [comment]
Well, just want to share some info that we tried to build anki-dict-helper similar function(one-click adding card with word, definition, context sentence) on iOS and Android in our language learning community. Just wondering, maybe you want to share within your community. It will be very useful especially while you reading on mobile device.

iOS anki-dict-helper function is based on iOS workflow & ankimobile beta which support URL scheme.
Android dict-helper is based on Ankidroid  RESTful API.

more detail is on anki support forum.
https://anki.tenderapp.com/discussions/ankimobile/5516-feature-request-ankimobile-url-scheme-for-add-note-by-using-lcpiftttworkflowdraft

**Comment by FooSoft** [comment]
This is cool stuff. I'm thinking that if this becomes a standard API for Anki Mobile and Anki Droid, it may be worthwhile to switch AnkiConnect to the same scheme.
