### ISSUE TITLE
Use Plugin without Anki?

### ISSUE THREAD

**Issue by NWuensche** [FooSoft/anki-connect#62]
Hi,

so I'd like to write a CLI-Tool for Anki. However, I can't use the Anki-GUI program itself, because I can't interact with it on the command line. Is there a way that I can still use this plugin, because I really like that you can do curl stuff with it.

Thanks,
Niklas

**Comment by FooSoft** [comment]
As long as you can launch the Anki graphical application (e.g. your system is capable of displaying a GUI), you should be able to use the plugin without any problems. Although Anki has to be running in the background, no user interaction is required once the application is launched (the API also includes a way to gracefully exit out).

**Comment by NWuensche** [comment]
Thanks for the answer!

But that's the problem for me. I want to run it on my server, where I just have the terminal and nothing more.

**Comment by FooSoft** [comment]
That would be a problem -- you can't really run the plugin if you can't run the host application. Admittedly it would not be the fanciest solution, you should be able to run barebones X11 even on a server. It should still be pretty light (don't need a desktop environment or anything), and Anki would still run.

**Comment by NWuensche** [comment]
Unfortunately, this doesn't work. I don't have sudo on the server, so I can't install much. And X11 doesn't really work without sudo

**Comment by NWuensche** [comment]
Just fixed my problem by using the web interface directly. If you like, you can find it here: https://github.com/NWuensche/ankicli . Thanks for the help nevertheless.

**Comment by FooSoft** [comment]
I would advise against this approach as it can lead to account ban (temporary or otherwise). I've experienced this firsthand working on my extension which did something similar. The author of Anki is actively trying to catch people who are using the web interface through automated means.

**Comment by tomasgodoi** [comment]
@NWuensche You can use my Anki docker image at https://hub.docker.com/r/txgio/anki/

**Comment by anishmittal2020** [comment]
> The author of Anki is actively trying to catch people who are using the web interface through automated means.

@FooSoft  Could you please tell what is the reasoning behind that this might  bother the author of anki? If its not a security issue, the author should not impose such restriction.

**Comment by hbnordin2** [comment]
@anishmittal2020 

Anki's free-tier is pretty generous. The author is probably paying for the servers and network traffic to run it. I think they might be trying to avoid having to either scale up or risk being browned out because of bots :)
