### ISSUE TITLE
Exposing an API for synchronize in anki-connect

### ISSUE THREAD

**Issue by sudarshang** [FooSoft/anki-connect#68]
Thanks for releasing anki-connect. It works great from the emacs anki-editor plugin. I want to add a command to the anki-editor plugin to ensure that new cards added from the plugin are synchronized to anki web so that I can access them from my ios app. For this to work the anki-connect plugin needs to expose an API that calls the anki sync functionality. Please let me know how I should go about implementing this.

**Comment by FooSoft** [comment]
It shouldn't be very difficult to accomplish I think. You will need to download the Anki source code and dig around it for the bit that causes synchronization to happen. You can then add a `@webApi` decorated method to the `AnkiConnect` class which forwards the relevant parameters to a method you will add in `AnkiBridge` class. That should be all that's required -- not sure if you had any more specific concerns.

**Comment by ewnd9** [comment]
I'm interested in this too, this is what I found in [`aqt/main.py:654`](https://github.com/dae/anki/blob/5cd063a8bd1936d371d779900c5aa50e71dd52b5/aqt/main.py#L654)

```py
# Syncing
##########################################################################

# expects a current profile and a loaded collection; reloads
# collection after sync completes
def onSync(self):
    self.unloadCollection(self._onSync)

def _onSync(self):
    self._sync()
    if not self.loadCollection():
        return

# expects a current profile, but no collection loaded
def maybeAutoSync(self):
    if (not self.pm.profile['syncKey']
        or not self.pm.profile['autoSync']
        or self.safeMode
        or self.restoringBackup):
        return

    # ok to sync
    self._sync()

def _sync(self):
    from aqt.sync import SyncManager
    self.state = "sync"
    self.syncer = SyncManager(self, self.pm)
    self.syncer.sync()
```

**Comment by sudarshang** [comment]
I asked about this on the Anki support forum see [here](https://anki.tenderapp.com/discussions/ankidesktop/27002-issuing-synchronize-from-an-anki-plugin). Feel free to chime in there.

**Comment by FooSoft** [comment]
@sudarshang I don't think you're going to get any technical support for messing around inside of the Anki code. You just jump in, get what you need and wire it up. We also don't need to ask permission for anything, since this is a very sane and reasonable feature.

@ewnd9 cool, looks like you found the relevant code. Seems like adding sync support would only take a couple of lines of code.

**Comment by FooSoft** [comment]
Merged

**Comment by FooSoft** [comment]
..and updated on AnkiWeb
