### ISSUE TITLE
Is there ability to create a new empty deck?

### ISSUE THREAD

**Issue by c-okelly** [FooSoft/anki-connect#70]
Apologies in advance if I have missed something in the docs but is there a specific action to create an empty deck? Or is there a reason that this functionality is not supported?

Thanks for releasing anki-connect!

**Comment by FooSoft** [comment]
You are correct in that there is currently no way to create an empty deck. There is no particular reason for this feature not existing, it's just that nobody has added it. I mostly created AnkiConnect for the Yomichan extension, and people have been sending pull requests for APIs that they want to use. 

You're welcome to send a pull request with this feature, it's probably just a couple of lines of code :+1:

**Comment by c-okelly** [comment]
Ahh cool. Thanks for the quick reply!

I will have a look at it!

**Comment by FooSoft** [comment]
Yeah just look at the Anki source in the areas where the AnkiConnect plugin pokes around in it for deck operations. It should be pretty simple to do I think.

**Comment by c-okelly** [comment]
Just opened a pull request there. Let me know if there is anything you would like changed!

**Comment by FooSoft** [comment]
Merged :+1:

**Comment by c-okelly** [comment]
Thanks for the quick comments, review and all the work in the first place!

**Comment by FooSoft** [comment]
Yup, feel free to propose or implement any other API features you need!
