### ISSUE TITLE
Errors are only reported on an exception

### ISSUE THREAD

**Issue by c-okelly** [FooSoft/anki-connect#72]
Hey,

I was using the api end point addNotes / addNote to insert new notes into the system and a noticed that there are a number of use cases where the note would fail to be created and the result would be None. There was no specific error message though as this two returned none.

Looking over the code I noticed that you only seem to return an error messages when an exception is thrown and caught. What would you think about refactoring the code to to include error messages when you have a logical failure.

An example of this might => attempt to add a new note. Deck specified doesn't exist. 
Results: None, Error: "The deck for specified note does note exist"

Just a suggestion anyway! 

Thanks,

C

**Comment by FooSoft** [comment]
This is a good point. The exception handling logic you are talking about is a remnant of a time when errors could not be reported via the API. It should be trivial to make them properly get reported to users of the API.

**Comment by c-okelly** [comment]
Ah makes sense! I would propose we create a custom exception class that could be used to throw an "action failed" exception with a more detailed error message. 

This could be caught by the existing code with no changes and the error message passed to back to the user?

It would also mean exceptions could be added incrementally. Let me know what you think!

C

**Comment by FooSoft** [comment]
I don't think we even need a custom exception class, you can just do something as simple as `raise Exception('everything is broken');` and it would work. Any and all exceptions are automatically caught by the `handler` method and stuffed into the `error` member. Basically the only thing that needs to happen is that exceptions need to be thrown when there are problems with data provided by the API.

**Comment by c-okelly** [comment]
Sounds good! I will work on something weekend and make a pull request.
