### ISSUE TITLE
Do you have any plans to make it possible to subscribe to events at Anki?

### ISSUE THREAD

**Issue by YahngSungho** [FooSoft/anki-connect#73]
For example, in the review mode, when the user chooses the difficulty of the card, it could be automatically notified of what it was.

**Comment by FooSoft** [comment]
I don't think that this would be possible since AnkiConnect works on a request-reply basis. There is no way for the server (Anki) to push events to your client.

**Comment by YahngSungho** [comment]
Thank you for your answer.
If I can not implement it directly, I'm going to use a hacky approach. It'd
takes the intervals of the cards and rwcalculates what is selected from SR
algorithm. And I hope I can automate using JS in cards of Anki.

2018. 3. 13. 오전 9:51에 "Alex Yatskov" <notifications@github.com>님이 작성:

**Comment by FooSoft** [comment]
Yeah I think something like that is going to be your best bet. I guess another possibility is to create some sort of "event queue" in AnkiConnect where events are put into a list and the client de-queues them. This could theoretically work but it gets strange if you ever have multiple clients working with the queue at the same time.
