### ISSUE TITLE
unsuspend method doesn't works

### ISSUE THREAD

**Issue by Dador** [FooSoft/anki-connect#74]
When trying to unsuspend the card I get the error:
```
AnkiBridge instance has no attribute "isSuspended"
```

That happened because in commit a6c15d7bb20ac099cecf728f05307c4317691fee `isSuspended` was changed and renamed to `areSuspended` but `unsuspend` code still uses `isSuspended` (which doesn't exists anymore).

The easiest solution is to add function `isSuspended` as it was: https://github.com/FooSoft/anki-connect/blob/dc01014daf1a9e7aeebdc0b15d39872cb3d7a150/AnkiConnect.py#L404-L409

**Comment by FooSoft** [comment]
Fixed
