### ISSUE TITLE
Space or other symbols between words within Deck name.

### ISSUE THREAD

**Issue by bikenik** [FooSoft/anki-connect#80]
Hello.
On the following points - doesn't works cause the Deck name has space or other symbols (e.g., brackets) between words:

* [deleteDecks]
* [findCards]
* ... [didn't check the rest of]

I can rename are existing and reformat the following, but maybe is it possible to add some regexp to fix this?

Thanks in advance.

**Comment by FooSoft** [comment]
I can't seem to repro this problem -- I ran the `test_deck.py` unit test with `test1` renamed to `test][` and `test 1 2 3` and both of those passed. Can you give me the actual JSON request that you sent? What error is reported by the way?

**Comment by bikenik** [comment]
I checked my workflow again and seems it's happening before the request to the Anki's API. 
Sorry to interrupt you.
my problem by the ```process.argv```

**Comment by FooSoft** [comment]
No worries, glad you figured it out.

**Comment by bikenik** [comment]
I hope that I don't wrong but checked this by different ways and was getting this error - ```"invalidSearch"```
with [findCards]
query: "deck:Murphy elementary" - err
query: "deck:Murphy-elementary" - OK
query: "deck:Murphy-(elementary)" - err

```js
try {
  for (const deck of decks) {
    ankiCards.push(await ankiConnect('findCards', 5,
      "params": {
        query: "deck:Murphy elementary"
      })
    )
}
} catch (err) {return err}        // "invalidSearch"
```

[deleteDecks] - works correct.

**Comment by FooSoft** [comment]
I can't seem to reproduce this problem -- unit tests pass even if I change deck names to those that you list as failing. What version of Anki are you running?

**Comment by bikenik** [comment]
... Forgot to test in Anki 2.0
#### macOs
- with Version 2.0.50
Qt 4.8.2 PyQt 4.9.4
avoids this error ("invalidSearch"), but returns an empty array for each deck without dependency of name format if at least one deck has space or another symbol.

- with Anki Version 2.1.0beta38 & 2.1.0beta39
Qt 5.9.2 PyQt 5.9
as I wrote above.

my goal is to get the count of cards for each deck as
```json
{
    "result": [1494723142483, 1494703460437, 1494703479525]
}
```
and than get count of "due" & "new" satus of each card.

![monosnap 2018-05-28 22-47-11](https://user-images.githubusercontent.com/20505855/40627719-49056892-62c9-11e8-8663-f3f2ad1177aa.png)

**Comment by bikenik** [comment]
In the end, it's my mistake.  )

`query: "deck:Foo name"` to `query: '"deck:Foo name"'` resolves this issue.
***

p.s. seems you have misprint [AnkiConnect.py#L762](https://github.com/FooSoft/anki-connect/blob/6882ca642ad7ac13920bd424c1702392a24512ba/AnkiConnect.py#L762) ("duo is not difined")

**Comment by FooSoft** [comment]
:+1:

**Comment by c-okelly** [comment]
I'm seeing the same issues with the following setup:

OS: MacOsx
Anki:Version 2.1.8 (71e0c880)
Qt 5.12.0 PyQt 5.11.3

I have a deck names => 0. ListNotes

Sent the following JSON
```json
{
    "action": "findNotes",
    "version": 6,
    "params": {
        "query": "deck:0. ListNotes'"
    }
}
```

Returned results was = []

When I send the following query is works:

```json
{
    "action": "findNotes",
    "version": 6,
    "params": {
        "query": "'deck:0. ListNotes'"
    }
}
```

Returned results was as expected

```json
{
    "result": [
        1556716932383
    ],
    "error": null
}
```

I'm not really sure if this is a bug or just a bit of a gotacha in the syntax used but def tripped me up. Would it be worth adding to the code to ensure the query is wrapped in quotes before it is send to Anki?

Or if not maybe just add a note in the documentation?

**Comment by abishekmuthian** [comment]
Adding few more examples,

On curl, The deck names with space needs to in quotes and escaped -

`curl  localhost:8675 -X POST -d '{"action": "findCards", "version": 6, "params":{"query":"\"deck:Fast AI\""}}'`

On Python, If the  example in the README is followed then just having the deck name in quotes is enough as  its encoded during request(although escaping doesn't hurt).

`result = invoke('findCards', query='"deck:Fast AI"')`

**Comment by oakkitten** [comment]
(This is just the way Anki search works. I suppose it follows the way shell strings work somewhat.

  * `deck:"foo bar"` (or `"deck:foo bar"`) will search for cards from the deck named `foo bar`;
  * `deck:foo bar` (or `deck:"foo" bar`, or `"deck:foo" bar`) will search for cards from the deck named `foo` containing the text `bar`.

This is not a special syntax of Anki-Connect)
