### ISSUE TITLE
Can't populate audio field/download media by API version 6 (It works from version 2 to version 5)

### ISSUE THREAD

**Issue by ninja33** [FooSoft/anki-connect#84]
Hi, I didn't change anything since ankiconnect v2 by using below XmlHttp call from my chrome extension.
my user feedback, they updated to most updated ankiconnect v6, seems it cannot download audio anymore. just wondering what's changed during recent update?

attached you may find xmlhttp call with json data (ankiconnect v6.0)

![image](https://user-images.githubusercontent.com/20181220/41775166-7128c0cc-7655-11e8-9fa2-cb01e2683117.png)

the same call can download audio with ankiconnect v5.0

![image](https://user-images.githubusercontent.com/20181220/41775286-f2dbf0e4-7655-11e8-9e7e-d753b29663ad.png)

**Comment by FooSoft** [comment]
I screwed up the download code during a recent refactor, sorry about that! A working version has been uploaded to AnkiWeb.

**Comment by ninja33** [comment]
tested, it's still not working

![image](https://user-images.githubusercontent.com/20181220/41805031-d64176a6-76d3-11e8-9b31-1814996e254e.png)

**Comment by FooSoft** [comment]
Hmm, could you copy paste the request you are trying to send in a code block? I think it should be working, strange.

**Comment by ninja33** [comment]
please check attached addnote.txt (windows format)

[addnote.txt](https://github.com/FooSoft/anki-connect/files/2129602/addnote.txt)

same request is successful under ankiconnect v5.0

**Comment by FooSoft** [comment]
I found and fixed another problem, everything should be good now. Let me know if it's not.

**Comment by ninja33** [comment]
It works. Thanks so much.
