### ISSUE TITLE
addNote should support duplicate notes...

### ISSUE THREAD

**Issue by burtonator** [FooSoft/anki-connect#98]
If I have a flashcard with the same field you prevent it from being added BUT the anki client itself can add it just fine as a duplicate card?

Duplicate cards are SUPPORTED just not recommended but anki connect blocks them.

I get the message "cannot create note because it is a duplicate"

I suggest adding a param of "allow_duplicates"

**Comment by alecschule** [comment]
Perhaps there should be a separate action for adding new cards? (to an existing note) In any case, something along these lines would be useful to me as well.

**Comment by bertoncelj1** [comment]
Instead of adding a new action I would suggest adding new field in note group called "options" where user could define parameters such as "allow_empty", "allow_duplicate" ... 

```
{
    "action": "addNotes",
    "version": 6,
    "params": {
        "notes": [
            {
                "deckName": "Default",
                "modelName": "Basic",
                "fields": {
                    "Front": "front content",
                    "Back": "back content"
                },
                "tags": [ "yomichan" ],
                "options": {
                     "allowDuplicate": true, 
                }
            }
        ]
    }
}
```

**Comment by burtonator** [comment]
Heck yeah.. that would be perfect for me.

**Comment by bertoncelj1** [comment]
Just out of curiosity, what are you developing that you need this feature?

**Comment by FooSoft** [comment]
The associated pull request has been merged and an updated version of the plugin has been uploaded to AnkiWeb :+1:

**Comment by burtonator** [comment]
WOW.. nice.  

I'm going to add this to the next version of Polar :) 

https://getpolarized.io/
